package io.arrogantprogrammer;

import java.util.List;

public class RandomAnimalService {

    public static String getRandomAnimal() {
        return ANIMALS.get((int) (Math.random() * ANIMALS.size()));
    }

    static final List<String> ANIMALS = List.of(
            "Aardvark",
            "African Civet",
            "African Palm Civet",
            "Amazon River Dolphin (Pink Dolphin)",
            "Anchovies",
            "Asian Palm Civet",
            "Asian Vine Snake",
            "Australian Retriever",
            "Avocet",
            "Banded Palm Civet",
            "Basset Fauve de Bretagne",
            "Bavarian Mountain Hound",
            "Bearded Vulture",
            "Beaver",
            "Belgian Tervuren",
            "Bouvier Des Flandres",
            "Bush Viper",
            "Carpet Viper",
            "Cava Tzu",
            "Cavador",
            "Cavalier King Charles Spaniel",
            "Cavapoo",
            "Chesapeake Bay Retriever",
            "Cinereous Vulture",
            "Common Raven",
            "Cross River Gorilla",
            "Curly Coated Retriever",
            "Czechoslovakian Wolfdog",
            "Devils Coach Horse Beetle",
            "Devon Rex",
            "Draco Volans Lizard",
            "Drever",
            "English Cream Golden Retriever",
            "Eurasian Beaver",
            "Evening Bat",
            "Eyelash Viper",
            "Flat-Coated Retriever",
            "Gaboon Viper",
            "Golden Retriever",
            "Griffon Vulture",
            "Havanese",
            "Havapoo",
            "Havashire",
            "Horned Viper",
            "Ivory-billed woodpecker",
            "Javan Rhinoceros",
            "Javanese",
            "King Vulture",
            "Kuvasz",
            "Labrador Retriever",
            "Lappet-faced Vulture",
            "Malayan Civet",
            "Mangrove Snake",
            "Masked Palm Civet",
            "Mojave Rattlesnake",
            "Mourning Dove",
            "Nova Scotia Duck Tolling Retriever",
            "Olive Baboon",
            "Orb Weaver",
            "Pennsylvania Wood Cockroach",
            "Pere Davids Deer",
            "Peruvian Inca Orchid",
            "Petit Basset Griffon Vendéen",
            "Red-Headed Vulture",
            "River Jack Snake",
            "River Otter",
            "River Turtle",
            "Sand Viper",
            "Savanna Goat",
            "Savannah Sparrow",
            "Serval",
            "Siberian Retriever",
            "Silver Dollar",
            "Silver Labrador",
            "Spider-Tailed Horned Viper",
            "Swedish Vallhund",
            "Tasmanian Devil",
            "Teddy Roosevelt Terrier",
            "Thorny Devil",
            "Transylvanian Hound",
            "Vampire Bat",
            "Vampire Squid",
            "Vaquita",
            "Venus Flytrap",
            "Vervet Monkey",
            "Vicuña",
            "Vinegaroon",
            "Viper shark (dogfish)",
            "Virgin Islands Dwarf Gecko",
            "Vizsla",
            "Volpino Italiano",
            "Vulture",
            "Water Vole",
            "Weaver Bird",
            "Wolverine",
            "Colossal Squid",
            "Crab-Eating Macaque",
            "Eastern Gray Squirrel",
            "Flying Squirrel",
            "Fox Squirrel",
            "Harlequin Snake",
            "Humboldt Squid",
            "Indian Giant Squirrel",
            "Indian Palm Squirrel",
            "Japanese Macaque",
            "Japanese Squirrel",
            "Macaque",
            "Mosquito",
            "Pesquet’s Parrot (Dracula Parrot)",
            "Quagga",
            "Quail",
            "Queen snake",
            "Quetzal",
            "Quokka",
            "Quoll",
            "Red Squirrel",
            "Red-Billed Quelea Bird",
            "Sea Squirt",
            "Squash Beetle",
            "Squid",
            "Squirrel",
            "Squirrel Monkey",
            "Squirrelfish",
            "Uinta Ground Squirrel",
            "Vampire Squid",
            "Vaquita",
            "Abyssinian",
            "African Grey Parrot",
            "Alaskan Husky",
            "Alusky",
            "American Pygmy Goat",
            "Armyworm",
            "Aye Aye",
            "Balkan Lynx",
            "Ball Python",
            "Banana Ball Python",
            "Baya",
            "Bilby",
            "Blood Python",
            "Blue Belly Lizard",
            "Blue Jay",
            "Blue Lacy Dog",
            "Blue Picardy Spaniel",
            "Bombay",
            "Booby",
            "Boxsky",
            "Boykin Spaniel",
            "Brittany",
            "Brown Hyena",
            "Burmese Python",
            "Bush Baby",
            "Butterfly",
            "Butterfly Fish",
            "Canada Lynx",
            "Capybara",
            "Carpet Python",
            "Cassowary",
            "Cat-Eyed Snake",
            "Cesky Fousek",
            "Cesky Terrier",
            "Chesapeake Bay Retriever",
            "Collared Peccary",
            "Coyote",
            "Curly Coated Retriever",
            "Donkey",
            "Dragonfly",
            "Dusky Dolphin",
            "Eastern Gray Squirrel",
            "Egyptian Cobra",
            "Egyptian Goose",
            "Egyptian Mau",
            "Eurasian Jay",
            "Eurasian Lynx",
            "Eyelash Viper",
            "Firefly",
            "Fly",
            "Flying Fish",
            "Flying Lemur",
            "Flying Snake",
            "Flying Squirrel",
            "Freshwater Jellyfish",
            "Fruit Fly",
            "Geoffroys Tamarin",
            "Gerberian Shepsky",
            "Golden Pyrenees",
            "Golden-Crowned Flying Fox",
            "Gray Fox",
            "Gray Tree Frog",
            "Great Crested Flycatcher",
            "Great Pyrenees",
            "Green Tree Python",
            "Grey Mouse Lemur",
            "Grey Reef Shark",
            "Grey Seal",
            "Greyhound",
            "Grizzly Bear",
            "Guppy",
            "Harpy Eagle",
            "Himalayan",
            "Hoary Bat",
            "Honey Badger",
            "Honey Bee",
            "Honey Buzzard",
            "Horsefly",
            "Housefly",
            "Howler Monkey",
            "Huntaway",
            "Husky",
            "Husky Jack",
            "Huskydoodle",
            "Hyena",
            "Immortal Jellyfish",
            "Italian Greyhound",
            "Ivory-billed woodpecker",
            "Jellyfish",
            "Kenyan Sand Boa",
            "Kerry Blue Terrier",
            "Key Deer",
            "Ladybug",
            "Lamprey",
            "Lawnmower Blenny",
            "Lion’s Mane Jellyfish",
            "Lynx",
            "Lyrebird",
            "Malayan Civet",
            "Malayan Tiger",
            "Man of War Jellyfish",
            "Manta Ray",
            "Mayfly",
            "Mealybug",
            "Miniature Husky",
            "Molly",
            "Monarch Butterfly",
            "Monkey",
            "Moon Jellyfish",
            "Moray Eel",
            "Mudpuppy",
            "Myna Bird",
            "Newfypoo",
            "Nyala",
            "Oyster",
            "Oyster Toadfish",
            "Patas Monkey",
            "Peacock Butterfly",
            "Pennsylvania Wood Cockroach",
            "Peringuey’s Adder",
            "Pied Ball Python",
            "Pink Fairy Armadillo",
            "Pitsky",
            "Platypus",
            "Polyphemus moth",
            "Pomsky",
            "Praying Mantis",
            "Proboscis Monkey",
            "Purple Emperor Butterfly",
            "Pygmy Hippopotamus",
            "Pygmy Marmoset (Finger Monkey)",
            "Pygora Goat",
            "Pyrador",
            "Pyredoodle",
            "Red-Eyed Tree Frog",
            "Rock Hyrax",
            "Rock Python",
            "Rottsky",
            "Royal Penguin",
            "Ruby-Throated Hummingbird",
            "Ruddy Turnstone",
            "Samoyed",
            "Scimitar-horned Oryx",
            "Sealyham Terrier",
            "Siberian Husky",
            "Silky Terrier",
            "Skye Terrier",
            "Smokybrown Cockroach",
            "Snowy Owl",
            "Sockeye Salmon",
            "Spider Ball Python",
            "Spider Monkey",
            "Spiny Dogfish",
            "Spiny Hill Turtle",
            "Spotted Lanternfly",
            "Squirrel Monkey",
            "Stabyhoun",
            "Stingray",
            "Striped Hyena",
            "Syrian Hamster",
            "Tawny Owl",
            "Teddy Bear Hamster",
            "Teddy Roosevelt Terrier",
            "Texas Spiny Lizard",
            "Thorny Devil",
            "Tiffany",
            "Toy Fox Terrier",
            "Toy Poodle",
            "Transylvanian Hound",
            "Tsetse Fly",
            "Turkey",
            "Venus Flytrap",
            "Vervet Monkey",
            "Wallaby",
            "Walleye Fish",
            "White Butterfly",
            "Woolly Mammoth",
            "Woolly Monkey",
            "Wyoming Toad",
            "X-Ray Tetra",
            "Yak",
            "Yakutian Laika",
            "Yarara",
            "Yellow Anaconda",
            "Yellow Sac Spider",
            "Yellow Spotted Lizard",
            "Yellow-Eyed Penguin",
            "Yellowfin Tuna",
            "Yeti Crab",
            "Yoranian",
            "Yorkie Bichon",
            "Yorkie-poo",
            "Yorkshire Terrier",
            "Zonkey",
            "Aardwolf",
            "Affenpinscher",
            "Afghan Hound",
            "African Bullfrog",
            "African Bush Elephant",
            "African Civet",
            "African Clawed Frog",
            "African Forest Elephant",
            "African Grey Parrot",
            "African Palm Civet",
            "African Penguin",
            "African Tree Toad",
            "African Wild Dog",
            "American Foxhound",
            "American Staffordshire Terrier",
            "Angelfish",
            "Anglerfish",
            "Angora Ferret",
            "Arafura File Snake",
            "Arctic Fox",
            "Arctic Wolf",
            "Banjo Catfish",
            "Barramundi Fish",
            "Basset Fauve de Bretagne",
            "Beefalo",
            "Betta Fish (Siamese Fighting Fish)",
            "Bichon Frise",
            "Bird Of Paradise",
            "Black-Footed Ferret",
            "Blobfish",
            "Blue Catfish",
            "Bluefin Tuna",
            "Bonito Fish",
            "Bouvier Des Flandres",
            "Bowfin",
            "Boxfish",
            "Brussels Griffon",
            "Buffalo",
            "Bullfrog",
            "Bullmastiff",
            "Burrowing Frog",
            "Butterfly",
            "Butterfly Fish",
            "Catfish",
            "Cesky Fousek",
            "Chinese Paddlefish",
            "Cinnamon Ferret",
            "Clownfish",
            "Cobia Fish",
            "Codfish",
            "Common Frog",
            "Common Furniture Beetle",
            "Crappie Fish",
            "Cross Fox",
            "Cuttlefish",
            "Czechoslovakian Wolfdog",
            "Darwin’s fox",
            "Darwin’s Frog",
            "Desert Rain Frog",
            "Dragonfish",
            "Dragonfly",
            "Drum Fish",
            "Dwarf Crocodile",
            "Dwarf Hamster",
            "Eastern Fence Lizard",
            "Edible Frog",
            "Electric Catfish",
            "English Foxhound",
            "Eurasian Wolf",
            "Falcon",
            "Fallow deer",
            "False Killer Whale",
            "False Widow Spider",
            "Fangtooth",
            "Feist",
            "Fennec Fox",
            "Fer-de-lance Snake",
            "Ferret",
            "Ferruginous Hawk",
            "Fiddler Crab",
            "Field Spaniel",
            "Fierce Snake",
            "Fila Brasileiro",
            "Fin Whale",
            "Finnish Spitz",
            "Fire Eel",
            "Fire salamander",
            "Fire-Bellied Toad",
            "Firefly",
            "Fisher Cat",
            "Fishing Cat",
            "Flamingo",
            "Flat-Coated Retriever",
            "Flea",
            "Florida Gar",
            "Florida Panther",
            "Florida Woods Cockroach",
            "Flounder",
            "Flowerhorn Fish",
            "Fluke Fish (summer flounder)",
            "Fly",
            "Flying Fish",
            "Flying Lemur",
            "Flying Snake",
            "Flying Squirrel",
            "Football Fish",
            "Formosan Mountain Dog",
            "Fossa",
            "Fox",
            "Fox Snakes",
            "Fox Squirrel",
            "Fox Terrier",
            "French Bulldog",
            "Frenchton",
            "Frengle",
            "Freshwater Crocodile",
            "Freshwater Eel",
            "Freshwater Jellyfish",
            "Frigatebird",
            "Frilled Lizard",
            "Frilled Shark",
            "Frog",
            "Frogfish",
            "Fruit Bat",
            "Fruit Fly",
            "Fur Seal",
            "Geoffroys Tamarin",
            "Ghost Catfish",
            "Giant African Land Snail",
            "Giraffe",
            "Glass Frog",
            "Glen Of Imaal Terrier",
            "Golden Newfie",
            "Golden-Crowned Flying Fox",
            "Goldfish",
            "Goliath Frog",
            "Gouldian Finch",
            "Gray Fox",
            "Gray Tree Frog",
            "Great Crested Flycatcher",
            "Green Frog",
            "Green Tree Frog",
            "Grey Reef Shark",
            "Griffon Vulture",
            "Griffonshire",
            "Guinea Fowl",
            "Hagfish",
            "Hardhead Catfish",
            "Horned Frog",
            "Horsefly",
            "House Finch",
            "Housefly",
            "Immortal Jellyfish",
            "Irish WolfHound",
            "Jellyfish",
            "Junglefowl",
            "Kingfisher",
            "Kit Fox",
            "Koi Fish",
            "Lappet-faced Vulture",
            "Leaf-Tailed Gecko",
            "Leopard Frog",
            "Lion’s Mane Jellyfish",
            "Lionfish",
            "Lizardfish",
            "Lumpfish",
            "Lungfish",
            "Mackenzie Wolf",
            "Mahi Mahi (Dolphin Fish)",
            "Man of War Jellyfish",
            "Maned Wolf",
            "Mantella Frog",
            "Marble Fox",
            "Marsh Frog",
            "Mastiff",
            "Mayfly",
            "Mekong Giant Catfish",
            "Mexican Free-Tailed Bat",
            "Midget Faded Rattlesnake",
            "Milkfish",
            "Mola mola (Ocean Sunfish)",
            "Monarch Butterfly",
            "Monkfish",
            "Moon Jellyfish",
            "Mountain Feist",
            "Neapolitan Mastiff",
            "Needlefish",
            "Newfoundland",
            "Newfypoo",
            "Norfolk Terrier",
            "Northern Fur Seal",
            "Norwegian Forest",
            "Oscar Fish",
            "Oyster Toadfish",
            "Paddlefish",
            "Parrotfish",
            "Peacock Butterfly",
            "Peregrine Falcon",
            "Petit Basset Griffon Vendéen",
            "Pike Fish",
            "Pink Fairy Armadillo",
            "Pipefish",
            "Poison Dart Frog",
            "Pool Frog",
            "Puff Adder",
            "Pufferfish",
            "Puffin",
            "Purple Emperor Butterfly",
            "Purple Finch",
            "Pygmy Marmoset (Finger Monkey)",
            "Ragamuffin",
            "Red Finch",
            "Red Fox",
            "Red Wolf",
            "Red-Eyed Tree Frog",
            "Red-Lipped Batfish",
            "Redtail Catfish",
            "Reef Shark",
            "Ringed Kingfisher",
            "Rockfish",
            "Saarloos Wolfdog",
            "Sable Ferret",
            "Satanic leaf-tailed gecko",
            "Sawfish",
            "Scorpion Fish",
            "Scrotum Frog",
            "Skate Fish",
            "Smooth Fox Terrier",
            "Southern Pacific Rattlesnake",
            "Spadefoot Toad",
            "Spanish Mastiff",
            "Spiny Dogfish",
            "Spotted Lanternfly",
            "Squirrelfish",
            "Staffordshire Bull Terrier",
            "Starfish",
            "Stargazer Fish",
            "Striped Rocket Frog",
            "Sucker Fish",
            "Surgeonfish",
            "Swai Fish",
            "Telescope Fish",
            "Tenterfield Terrier",
            "Tibetan Fox",
            "Tibetan Mastiff",
            "Tiffany",
            "Toadfish",
            "Toy Fox Terrier",
            "Tree Frog",
            "Tsetse Fly",
            "Venus Flytrap",
            "Viper shark (dogfish)",
            "Virgin Islands Dwarf Gecko",
            "Wahoo Fish",
            "Walking Catfish",
            "Walleye Fish",
            "Water Buffalo",
            "Wels Catfish",
            "White Butterfly",
            "White Ferret / Albino Ferrets",
            "White-Faced Capuchin",
            "Wire Fox Terrier",
            "Wirehaired Pointing Griffon",
            "Wolf",
            "Wolf Eel",
            "Wolf Snake",
            "Wolf Spider",
            "Wolffish",
            "Wood Frog",
            "Yellowfin Tuna",
            "Zebra Finch",
            "Abyssinian",
            "Adelie Penguin",
            "Aesculapian snake",
            "Affenpinscher",
            "Afghan Hound",
            "African Bullfrog",
            "African Bush Elephant",
            "African Civet",
            "African Clawed Frog",
            "African Forest Elephant",
            "African Grey Parrot",
            "African Palm Civet",
            "African Penguin",
            "African Tree Toad",
            "African Wild Dog",
            "Ainu",
            "Alaskan Husky",
            "Alaskan Klee Kai",
            "Alaskan Malamute",
            "Alaskan Shepherd",
            "Albacore Tuna",
            "Aldabra Giant Tortoise",
            "Alpine Dachsbracke",
            "Alpine Goat",
            "Amazon Parrot",
            "Amazon River Dolphin (Pink Dolphin)",
            "American Alsatian",
            "American Bulldog",
            "American Cocker Spaniel",
            "American Cockroach",
            "American Coonhound",
            "American Dog Tick",
            "American Eskimo Dog",
            "American Foxhound",
            "American Hairless Terrier",
            "American Leopard Hound",
            "American Pit Bull Terrier",
            "American Pygmy Goat",
            "American Robin",
            "American Staffordshire Terrier",
            "American Toad",
            "American Water Spaniel",
            "Anaconda",
            "Anatolian Shepherd Dog",
            "Anchovies",
            "Angelfish",
            "Anglerfish",
            "Angora Ferret",
            "Angora Goat",
            "Anole Lizard",
            "Ant",
            "Antarctic scale worm",
            "Anteater",
            "Antelope",
            "Appenzeller Dog",
            "Arafura File Snake",
            "Arizona Bark Scorpion",
            "Arizona Black Rattlesnake",
            "Aruba Rattlesnake",
            "Asian Cockroach",
            "Asian Elephant",
            "Asian Giant Hornet",
            "Asian Palm Civet",
            "Asian Vine Snake",
            "Assassin Bug",
            "Australian Bulldog",
            "Australian Cattle Dog",
            "Australian Cockroach",
            "Australian Gecko",
            "Australian Kelpie Dog",
            "Australian Labradoodle",
            "Australian Mist",
            "Australian Retriever",
            "Australian Shepherd",
            "Australian Terrier",
            "Baboon",
            "Bactrian Camel",
            "Baleen Whale",
            "Balinese",
            "Balkan Lynx",
            "Ball Python",
            "Banana Ball Python",
            "Banana Eel",
            "Banana Spider",
            "Banded Palm Civet",
            "Banded Water Snake",
            "Bandicoot",
            "Banjo Catfish",
            "Barn Owl",
            "Barn Swallow",
            "Barnacle",
            "Barramundi Fish",
            "Basenji Dog",
            "Basking Shark",
            "Basset Fauve de Bretagne",
            "Basset Hound",
            "Bavarian Mountain Hound",
            "Bearded Dragon",
            "Beauceron",
            "Bedlington Terrier",
            "Belgian Shepherd",
            "Belgian Tervuren",
            "Beluga Sturgeon",
            "Bengal Tiger",
            "Bernedoodle",
            "Bernese Mountain Dog",
            "Bernese Shepherd",
            "Betta Fish (Siamese Fighting Fish)",
            "Bichon Frise",
            "Bighorn Sheep",
            "Binturong",
            "Birman",
            "Bison",
            "Black And Tan Coonhound",
            "Black Marlin",
            "Black Rat Snake",
            "Black Rhinoceros",
            "Black Russian Terrier",
            "Blanket Octopus",
            "Blood Python",
            "Bloodhound",
            "Blue Iguana",
            "Blue Picardy Spaniel",
            "Blue-Ringed Octopus",
            "Bluefin Tuna",
            "Bluetick Coonhound",
            "Bobolink",
            "Boglen Terrier",
            "Bolognese Dog",
            "Bongo",
            "Bonito Fish",
            "Bonnethead Shark",
            "Bonobo",
            "Boomslang",
            "Bornean Orang-utan",
            "Borneo Elephant",
            "Boston Terrier",
            "Bottlenose Dolphin",
            "Bouvier Des Flandres",
            "Bowfin",
            "Boykin Spaniel",
            "Brazilian Terrier",
            "Brittany",
            "Brown Bear",
            "Brown Dog Tick",
            "Brown Hyena",
            "Brown Snake",
            "Brown Water Snake",
            "Brown-banded Cockroach",
            "Brussels Griffon",
            "Bullsnake",
            "Burmese Python",
            "Burrowing Frog",
            "Burrowing Owl",
            "Bushmaster Snake",
            "Caecilian",
            "Caiman",
            "Caiman Lizard",
            "Cairn Terrier",
            "Canaan Dog",
            "Canada Lynx",
            "Canadian Eskimo Dog",
            "Canadian Horse",
            "Cane Corso",
            "Cantil",
            "Cape Lion",
            "Carolina Dog",
            "Carolina Parakeet",
            "Carpenter Ant",
            "Carpet Python",
            "Cat-Eyed Snake",
            "Catalan Sheepdog",
            "Cavalier King Charles Spaniel",
            "Centipede",
            "Chameleon",
            "Chicken",
            "Chicken Snake",
            "Chimpanzee",
            "Chinchilla",
            "Chinese Alligator",
            "Chinese Crested Dog",
            "Chinese Geese",
            "Chinese Paddlefish",
            "Chinese Shar-Pei",
            "Chinook",
            "Chinook Salmon",
            "Chinstrap Penguin",
            "Chipmunk",
            "Chipping Sparrow",
            "Chiweenie",
            "Christmas Island Red Crab",
            "Cinereous Vulture",
            "Cinnamon Ferret",
            "Clownfish",
            "Clumber Spaniel",
            "Coachwhip Snake",
            "Cocker Spaniel",
            "Coelacanth",
            "Collett’s Snake",
            "Common Buzzard",
            "Common European Adder",
            "Common Frog",
            "Common Furniture Beetle",
            "Common House Spider",
            "Common Loon",
            "Common Raven",
            "Common Toad",
            "Conger Eel",
            "Congo Snake",
            "Coral Snake",
            "Corman Shepherd",
            "Corn Rex Cat (Cornish Rex)",
            "Corn Snake",
            "Coton de Tulear",
            "Cotton-top Tamarin",
            "Cottonmouth",
            "Crab-Eating Macaque",
            "Crane",
            "Crested Penguin",
            "Crucian Carp",
            "Cuban Cockroach",
            "Czechoslovakian Wolfdog",
            "Dachshund",
            "Dalmatian",
            "Danios",
            "Dapple Dachshund",
            "Darwin’s fox",
            "Darwin’s Frog",
            "Desert Rain Frog",
            "Devon Rex",
            "Dingo",
            "Doberman Pinscher",
            "Dogo Argentino",
            "Dolphin",
            "Donkey",
            "Draco Volans Lizard",
            "Dragonfish",
            "Dragonfly",
            "Dugong",
            "Dung Beetle",
            "Dunker",
            "Dunnock",
            "Dusky Dolphin",
            "Eastern Barred Bandicoot",
            "Eastern Bluebird",
            "Eastern Brown Snake",
            "Eastern Chipmunk",
            "Eastern Diamondback Rattlesnake",
            "Eastern Fence Lizard",
            "Eastern Glass Lizard",
            "Eastern Gorilla",
            "Eastern Gray Squirrel",
            "Eastern Indigo Snake",
            "Eastern Lowland Gorilla",
            "Eastern Phoebe",
            "Eastern Rat snake",
            "Eastern Woodrat",
            "Echidna",
            "Egyptian Cobra",
            "Egyptian Goose",
            "Egyptian Mau",
            "Eland",
            "Elegant Tern",
            "Elephant",
            "Elephant Seal",
            "Elephant Shrew",
            "Emerald Tree Monitor",
            "Emperor Penguin",
            "Emperor Tamarin",
            "English Bulldog",
            "English Cocker Spaniel",
            "English Cream Golden Retriever",
            "English Foxhound",
            "English Pointer",
            "English Setter",
            "English Shepherd",
            "English Springer Spaniel",
            "Entlebucher Mountain Dog",
            "Epagneul Pont Audemer",
            "Ermine",
            "Estrela Mountain Dog",
            "Eurasian Beaver",
            "Eurasian Jay",
            "Eurasian Lynx",
            "Eurasian Nuthatch",
            "Eurasian Wolf",
            "European Bee-Eater",
            "European Polecat",
            "European Robin",
            "European Wildcat",
            "Evening Bat",
            "Falcon",
            "Fangtooth",
            "Fennec Fox",
            "Fer-de-lance Snake",
            "Ferruginous Hawk",
            "Field Spaniel",
            "Fierce Snake",
            "Fin Whale",
            "Finnish Spitz",
            "Fire salamander",
            "Fishing Cat",
            "Flamingo",
            "Florida Panther",
            "Flounder",
            "Flowerhorn Fish",
            "Fluke Fish (summer flounder)",
            "Flying Fish",
            "Flying Lemur",
            "Flying Snake",
            "Flying Squirrel",
            "Formosan Mountain Dog",
            "Fox Snakes",
            "French Bulldog",
            "Frenchton",
            "Frengle",
            "Gaboon Viper",
            "Galapagos Penguin",
            "Garden Eel",
            "Garter Snake",
            "Genet",
            "Gentoo Penguin",
            "Geoffroys Tamarin",
            "Gerberian Shepsky",
            "German Cockroach",
            "German Pinscher",
            "German Shepherd Guide",
            "German Sheppit",
            "German Sheprador",
            "German Shorthaired Pointer",
            "German Spitz",
            "Giant African Land Snail",
            "Giant Armadillo",
            "Giant Clam",
            "Giant Panda Bear",
            "Giant Salamander",
            "Giant Schnauzer",
            "Giant Schnoodle",
            "Gibbon",
            "Gila Monster",
            "Glechon",
            "Glen Of Imaal Terrier",
            "Gnat",
            "Goberian",
            "Goblin Shark",
            "Golden Dox",
            "Golden Lancehead",
            "Golden Lion Tamarin",
            "Golden Masked Owl",
            "Golden Newfie",
            "Golden Oriole",
            "Golden Pyrenees",
            "Golden Retriever",
            "Golden Saint",
            "Golden Shepherd",
            "Golden-Crowned Flying Fox",
            "Goldendoodle",
            "Gopher Snake",
            "Gordon Setter",
            "Gouldian Finch",
            "Grass Snake",
            "Great Blue Heron",
            "Great Dane",
            "Great Danoodle",
            "Great Pyrenees",
            "Greater Swiss Mountain Dog",
            "Green Anole",
            "Green Bee-Eater",
            "Green Frog",
            "Green Mamba",
            "Green Tree Frog",
            "Green Tree Python",
            "Greenland Dog",
            "Greenland Shark",
            "Greyhound",
            "Griffon Vulture",
            "Griffonshire",
            "Groenendael",
            "Ground Snake",
            "Groundhog (Woodchuck)",
            "Guinea Fowl",
            "Guinea Pig",
            "Habu Snake",
            "Harlequin Snake",
            "Havanese",
            "Hawaiian Crow",
            "Hawaiian Goose",
            "Hawaiian Monk Seal",
            "Hellbender",
            "Heron",
            "Herring",
            "Highland Cattle",
            "Himalayan",
            "Honduran White Bat",
            "Honey Badger",
            "Honey Bee",
            "Honey Buzzard",
            "Horn Shark",
            "Hornbill",
            "Horned Adder",
            "Horned Frog",
            "Horned Lizard",
            "Horned Viper",
            "House Finch",
            "House wren",
            "Howler Monkey",
            "Human",
            "Humboldt Penguin",
            "Hummingbird",
            "Huntaway",
            "Huntsman Spider",
            "Hyena",
            "Ibizan Hound",
            "Icelandic Sheepdog",
            "Iguana",
            "Indian Cobra",
            "Indian Elephant",
            "Indian Giant Squirrel",
            "Indian Palm Squirrel",
            "Indian Rhinoceros",
            "Indian Star Tortoise",
            "Indigo Snake",
            "Indochinese Tiger",
            "Indri",
            "Insect",
            "Irish Water Spaniel",
            "Irish WolfHound",
            "Italian Greyhound",
            "Jacana",
            "Jackson’s Chameleon",
            "Jaguarundi Cat",
            "Japanese Beetle",
            "Japanese Chin",
            "Japanese Macaque",
            "Japanese Spitz",
            "Japanese Squirrel",
            "Japanese Terrier",
            "Javan Rhinoceros",
            "Javanese",
            "Jonah Crab",
            "Jumping Spider",
            "Junglefowl",
            "Kai Ken",
            "Kangal",
            "Kangaroo",
            "Kangaroo Rat",
            "Keel-Billed Toucan",
            "Keeshond",
            "Kenyan Sand Boa",
            "Keta Salmon",
            "Kinder Goat",
            "King Cobra",
            "King Crab",
            "King Penguin",
            "King Shepherd",
            "King Snake",
            "King Vulture",
            "Kingfisher",
            "Kinkajou",
            "Kirtland’s snake",
            "Komodo Dragon",
            "Kooikerhondje",
            "Labmaraner",
            "Labradane",
            "Lake Sturgeon",
            "Lakeland Terrier",
            "LaMancha Goat",
            "Lancashire Heeler",
            "Lapponian Herder",
            "Lawnmower Blenny",
            "Lemming",
            "Leonberger",
            "Lion",
            "Lion’s Mane Jellyfish",
            "Lionfish",
            "Little Brown Bat",
            "Little Penguin",
            "Lone Star Tick",
            "Long-Eared Owl",
            "Long-Haired Rottweiler",
            "Long-Tailed Tit",
            "Longnose Gar",
            "Lowchen",
            "Lungfish",
            "Lynx",
            "Macaroni Penguin",
            "Mackenzie Wolf",
            "Madagascar Hissing Cockroach",
            "Magellanic Penguin",
            "Mahi Mahi (Dolphin Fish)",
            "Maine Coon",
            "Malayan Civet",
            "Malayan Tiger",
            "Mamushi Snake",
            "Man of War Jellyfish",
            "Manatee",
            "Manchester Terrier",
            "Mandrill",
            "Maned Wolf",
            "Mangrove Snake",
            "Manta Ray",
            "Mantella Frog",
            "Marine Iguana",
            "Marine Toad",
            "Megalodon",
            "Mekong Giant Catfish",
            "Mexican Alligator Lizard",
            "Mexican Black Kingsnake",
            "Mexican Eagle (Northern crested caracara)",
            "Mexican Free-Tailed Bat",
            "Mexican Mole Lizard",
            "Midget Faded Rattlesnake",
            "Milk Snake",
            "Mini Labradoodle",
            "Miniature Bull Terrier",
            "Miniature Husky",
            "Miniature Pinscher",
            "Mink",
            "Minke Whale",
            "Moccasin Snake",
            "Mojave Rattlesnake",
            "Mola mola (Ocean Sunfish)",
            "Mole Snake",
            "Monarch Butterfly",
            "Mongoose",
            "Mongrel",
            "Monitor Lizard",
            "Monkey",
            "Monkfish",
            "Monte Iberia Eleuth",
            "Moon Jellyfish",
            "Moorhen",
            "Mountain Bluebird",
            "Mountain Cur",
            "Mountain Feist",
            "Mountain Gorilla",
            "Mountain Lion",
            "Mourning Dove",
            "Mud Snake",
            "Mulga Snake",
            "Muntjac",
            "Mussurana Snake",
            "Myna Bird",
            "Naked Mole Rat",
            "Narwhal",
            "Natterjack",
            "Neanderthal",
            "Neapolitan Mastiff",
            "Nebelung",
            "Needlefish",
            "Newfoundland",
            "Newfypoo",
            "Newt",
            "Nicobar pigeon",
            "Nigerian Goat",
            "Night Adder",
            "Nightingale",
            "Nile Crocodile",
            "Nilgai",
            "No See Ums",
            "Norfolk Terrier",
            "North American Black Bear",
            "Northern Alligator Lizard",
            "Northern Cardinal",
            "Northern Fur Seal",
            "Northern Inuit Dog",
            "Northern Water Snake",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwegian Forest",
            "Norwegian Lundehund",
            "Norwich Terrier",
            "Nova Scotia Duck Tolling Retriever",
            "Nubian Goat",
            "Nudibranch",
            "Numbat",
            "Nurse Shark",
            "Nyala",
            "Old English Sheepdog",
            "Olive Baboon",
            "Orang-utan",
            "Orange-Crowned Warbler",
            "Ortolan Bunting",
            "Otterhound",
            "Pademelon",
            "Painted Turtle",
            "Pangolin",
            "Panther",
            "Papillon",
            "Parrot Snake",
            "Parson Russell Terrier",
            "Patas Monkey",
            "Pekingese",
            "Pelican",
            "Penguin",
            "Pennsylvania Wood Cockroach",
            "Peregrine Falcon",
            "Peringuey’s Adder",
            "Perro De Presa Canario",
            "Persian",
            "Peruvian Inca Orchid",
            "Petit Basset Griffon Vendéen",
            "Petite Goldendoodle",
            "Pheasant",
            "Pied Ball Python",
            "Pied Tamarin",
            "Pigeon",
            "Pine Marten",
            "Pine Snake",
            "Pine Snake",
            "Pink Fairy Armadillo",
            "Piranha",
            "Pointer",
            "Poison Dart Frog",
            "Polish Lowland Sheepdog",
            "Pomeranian",
            "Pond Skater",
            "Poochon",
            "Porcupine",
            "Prairie Rattlesnake",
            "Prawn",
            "Praying Mantis",
            "Proboscis Monkey",
            "Pronghorn",
            "Pudelpointer",
            "Puffin",
            "Purple Finch",
            "Pygmy Marmoset (Finger Monkey)",
            "Queen snake",
            "Raccoon",
            "Raccoon Dog",
            "Ragamuffin",
            "Rainbow Boa",
            "Rat Snakes",
            "Rattlesnake",
            "Red Diamondback Rattlesnake",
            "Red Finch",
            "Red Knee Tarantula",
            "Red Panda",
            "Red Tail Boa (common boa)",
            "Red-Bellied Black Snake",
            "Red-handed Tamarin",
            "Red-winged blackbird",
            "Redbone Coonhound",
            "Reindeer",
            "Rhinoceros",
            "Rhombic Egg-Eater Snake",
            "Ribbon Eel",
            "Ribbon Snake",
            "Ringed Kingfisher",
            "Rinkhals Snake",
            "River Jack Snake",
            "Robin",
            "Rock Python",
            "Rockhopper Penguin",
            "Rodents",
            "Roseate Spoonbill",
            "Rough Green Snake",
            "Royal Penguin",
            "Ruby-Throated Hummingbird",
            "Ruddy Turnstone",
            "Russian Bear Dog",
            "Russian Blue",
            "Russian Tortoise",
            "Saanen Goat",
            "Sable Black German Shepherd",
            "Saint Berdoodle",
            "Saint Bernard",
            "Saint Shepherd",
            "Salamander",
            "Salmon",
            "Salmon Shark",
            "Sand Crab",
            "Sand Lizard",
            "Sand Tiger Shark",
            "Sand Viper",
            "Sardines",
            "Satanic leaf-tailed gecko",
            "Savanna Goat",
            "Savannah Sparrow",
            "Scarlet Kingsnake",
            "Schneagle",
            "Schnoodle",
            "Scimitar-horned Oryx",
            "Scorpion",
            "Scorpion Fish",
            "Sea Anemone",
            "Sea Dragon",
            "Sea Lion",
            "Sea Urchin",
            "Senegal Parrot",
            "Sharp-Tailed Snake",
            "Shiba Inu",
            "Siberian",
            "Siberian Husky",
            "Siberian Ibex",
            "Siberian Retriever",
            "Siberian Tiger",
            "Silkie Chicken",
            "Skink Lizard",
            "Skipjack Tuna",
            "Skunk",
            "Smokybrown Cockroach",
            "Snail",
            "Snake",
            "Snapping Turtle",
            "Snorkie",
            "Snouted Cobra",
            "Snow Crab",
            "Snow Leopard",
            "Snowshoe",
            "Snowshoe Hare",
            "Snowy Owl",
            "Sockeye Salmon",
            "Song Sparrow",
            "Song Thrush",
            "South China Tiger",
            "Southern Black Racer",
            "Southern Pacific Rattlesnake",
            "Spanador",
            "Spanish Goat",
            "Spanish Mastiff",
            "Spider Ball Python",
            "Spider Monkey",
            "Spider-Tailed Horned Viper",
            "Spinner Shark",
            "Spinone Italiano",
            "Spiny Dogfish",
            "Spiny Hill Turtle",
            "Spitting Cobra",
            "Sponge",
            "Spotted Lanternfly",
            "Springador",
            "Springbok",
            "Springerdoodle",
            "Squirrel Monkey",
            "Sri Lankan Elephant",
            "Stabyhoun",
            "Standard Schnauzer",
            "Star-nosed mole",
            "Steelhead Salmon",
            "Stick Insect",
            "Stiletto Snake",
            "Stingray",
            "Stone Crab",
            "Striped Hyena",
            "Sturgeon",
            "Sumatran Elephant",
            "Sumatran Orang-utan",
            "Sumatran Rhinoceros",
            "Sumatran Tiger",
            "Sun Bear",
            "Surgeonfish",
            "Swan",
            "Swedish Vallhund",
            "Syrian Hamster",
            "Takin",
            "Tamaskan",
            "Tang",
            "Tapanuli Orang-utan",
            "Tarantula Hawk",
            "Tarpon",
            "Tasmanian Devil",
            "Tasmanian Tiger",
            "Tawny Owl",
            "Tennessee Walker Horse",
            "Tenterfield Terrier",
            "Texas Indigo Snake",
            "Texas Rat Snake",
            "Texas Spiny Lizard",
            "Thorny Devil",
            "Tibetan Fox",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Tiffany",
            "Tiger Rattlesnake",
            "Tiger Salamander",
            "Timber Rattlesnake (Canebrake Rattlesnake)",
            "Toucan",
            "Transylvanian Hound",
            "Tree Kangaroo",
            "Tree Snake",
            "Treeing Tennessee Brindle",
            "Treeing Walker Coonhound",
            "Tuna",
            "Turkish Angora",
            "Twig Snake",
            "Uinta Ground Squirrel",
            "Unau (Linnaeus’s Two-Toed Sloth)",
            "Urutu Snake",
            "Utonagan",
            "Venus Flytrap",
            "Vervet Monkey",
            "Vinegaroon",
            "Virgin Islands Dwarf Gecko",
            "Volpino Italiano",
            "Walking Catfish",
            "Wandering Albatross",
            "Water Dragon",
            "Weimaraner",
            "West Highland Terrier",
            "Western Diamondback Rattlesnake",
            "Western Gorilla",
            "Western Hognose Snake",
            "Western Lowland Gorilla",
            "Western Rat Snake",
            "Wheaten Terrier",
            "Whinchat",
            "White Ferret / Albino Ferrets",
            "White Rhinoceros",
            "White-Faced Capuchin",
            "Whooping Crane",
            "Wirehaired Pointing Griffon",
            "Wolf Snake",
            "Wolverine",
            "Wood Bison",
            "Woolly Monkey",
            "Worm Snake",
            "Writing Spider",
            "Wyoming Toad",
            "Xoloitzcuintli",
            "Yakutian Laika",
            "Yellow Anaconda",
            "Yellow-Eyed Penguin",
            "Yellowfin Tuna",
            "Yoranian",
            "Yorkie Bichon",
            "Zebra Finch",
            "Zebra Snake",
            "Zonkey",
            "Zuchon",
            "Aardvark",
            "Aardwolf",
            "Abyssinian",
            "Addax",
            "Adelie Penguin",
            "Aesculapian snake",
            "Affenpinscher",
            "Afghan Hound",
            "African Bullfrog",
            "African Bush Elephant",
            "African Civet",
            "African Clawed Frog",
            "African Forest Elephant",
            "African Grey Parrot",
            "African Palm Civet",
            "African Penguin",
            "African Tree Toad",
            "African Wild Dog",
            "Agama Lizard",
            "Aidi",
            "Ainu",
            "Airedale Terrier",
            "Airedoodle",
            "Akbash",
            "Akita",
            "Akita Shepherd",
            "Alabai",
            "Alaskan Husky",
            "Alaskan Klee Kai",
            "Alaskan Malamute",
            "Alaskan Shepherd",
            "Albacore Tuna",
            "Albatross",
            "Aldabra Giant Tortoise",
            "Alligator",
            "Alligator Gar",
            "Alpaca",
            "Alpine Dachsbracke",
            "Alpine Goat",
            "Alusky",
            "Amazon Parrot",
            "Amazon River Dolphin (Pink Dolphin)",
            "Ambrosia Beetle",
            "American Alsatian",
            "American Bulldog",
            "American Cocker Spaniel",
            "American Cockroach",
            "American Coonhound",
            "American Dog Tick",
            "American Eskimo Dog",
            "American Foxhound",
            "American Hairless Terrier",
            "American Leopard Hound",
            "American Pit Bull Terrier",
            "American Pygmy Goat",
            "American Robin",
            "American Staffordshire Terrier",
            "American Toad",
            "American Water Spaniel",
            "Amur Leopard",
            "Anaconda",
            "Anatolian Shepherd Dog",
            "Anchovies",
            "Angelfish",
            "Anglerfish",
            "Angora Ferret",
            "Angora Goat",
            "Anole Lizard",
            "Ant",
            "Antarctic scale worm",
            "Anteater",
            "Antelope",
            "Ape",
            "Appenzeller Dog",
            "Apple Head Chihuahua",
            "Arafura File Snake",
            "Arapaima",
            "Arctic Fox",
            "Arctic Hare",
            "Arctic Wolf",
            "Arizona Bark Scorpion",
            "Arizona Black Rattlesnake",
            "Armadillo",
            "Armadillo Lizard",
            "Armyworm",
            "Aruba Rattlesnake",
            "Asian Cockroach",
            "Asian Elephant",
            "Asian Giant Hornet",
            "Asian Palm Civet",
            "Asian Vine Snake",
            "Asiatic Black Bear",
            "Asp",
            "Assassin Bug",
            "Aurochs",
            "Aussiedoodle",
            "Aussiedor",
            "Australian Bulldog",
            "Australian Cattle Dog",
            "Australian Cockroach",
            "Australian Gecko",
            "Australian Kelpie Dog",
            "Australian Labradoodle",
            "Australian Mist",
            "Australian Retriever",
            "Australian Shepherd",
            "Australian Terrier",
            "Avocet",
            "Axolotl",
            "Aye Aye",
            "Babirusa",
            "Baboon",
            "Bactrian Camel",
            "Badger",
            "Baiji",
            "Bald Eagle",
            "Baleen Whale",
            "Balinese",
            "Balkan Lynx",
            "Ball Python",
            "Banana Ball Python",
            "Banana Eel",
            "Banana Spider",
            "Banded Palm Civet",
            "Banded Water Snake",
            "Bandicoot",
            "Banjo Catfish",
            "Barb",
            "Barbet",
            "Barn Owl",
            "Barn Swallow",
            "Barnacle",
            "Barracuda",
            "Barramundi Fish",
            "Barred Owl",
            "Basenji Dog",
            "Basilisk Lizard",
            "Basking Shark",
            "Bassador",
            "Basset Fauve de Bretagne",
            "Basset Hound",
            "Bassetoodle",
            "Bat",
            "Bavarian Mountain Hound",
            "Baya",
            "Bea-Tzu",
            "Beabull",
            "Beagador",
            "Beagle",
            "Beagle Shepherd",
            "Beaglier",
            "Beago",
            "Bear",
            "Bearded Collie",
            "Bearded Dragon",
            "Bearded Vulture",
            "Beaski",
            "Beauceron",
            "Beaver",
            "Beefalo",
            "Belgian Shepherd",
            "Belgian Tervuren",
            "Beluga Sturgeon",
            "Bengal Tiger",
            "Bergamasco",
            "Berger Picard",
            "Bernese Mountain Dog",
            "Betta Fish (Siamese Fighting Fish)",
            "Bird Of Paradise",
            "Birman",
            "Black And Tan Coonhound",
            "Black Mamba",
            "Black Marlin",
            "Black Rat Snake",
            "Black Rhinoceros",
            "Black Russian Terrier",
            "Black Wasp",
            "Black Widow Spider",
            "Black-Capped Chickadee",
            "Black-Footed Ferret",
            "Blackpoll Warbler",
            "Blanket Octopus",
            "Blue Belly Lizard",
            "Blue Catfish",
            "Blue grosbeak",
            "Blue Iguana",
            "Blue Jay",
            "Blue Lacy Dog",
            "Blue Picardy Spaniel",
            "Blue Shark",
            "Blue Whale",
            "Bluefin Tuna",
            "Bobcat",
            "Boiga",
            "Bombay",
            "Bonnethead Shark",
            "Boomslang",
            "Borador",
            "Bornean Orang-utan",
            "Borneo Elephant",
            "Bouvier Des Flandres",
            "Bowhead Whale",
            "Boxador",
            "Boykin Spaniel",
            "Brazilian Terrier",
            "Brittany",
            "Brookesia Micra",
            "Brown Bear",
            "Brown Hyena",
            "Brown Snake",
            "Brown Water Snake",
            "Brown-banded Cockroach",
            "Budgerigar",
            "Buffalo",
            "Bull Shark",
            "Bullmastiff",
            "Bullsnake",
            "Bush Baby",
            "Bushmaster Snake",
            "Cactus Mouse",
            "Caecilian",
            "Caiman",
            "Caiman Lizard",
            "Cairn Terrier",
            "Camel",
            "Camel Cricket",
            "Camel Spider",
            "Canaan Dog",
            "Canada Lynx",
            "Canadian Eskimo Dog",
            "Canadian Horse",
            "Cane Corso",
            "Cantil",
            "Cape Lion",
            "Capybara",
            "Caracal",
            "Caribou",
            "Carolina Dog",
            "Carolina Parakeet",
            "Carp",
            "Carpenter Ant",
            "Carpet Python",
            "Carpet Viper",
            "Cascabel",
            "Cashmere Goat",
            "Cassowary",
            "Cat-Eyed Snake",
            "Catahoula Leopard",
            "Catalan Sheepdog",
            "Caterpillar",
            "Catfish",
            "Cava Tzu",
            "Cavador",
            "Cavalier King Charles Spaniel",
            "Cavapoo",
            "Cecropia Moth",
            "Chameleon",
            "Chamois",
            "Chartreux",
            "Cheagle",
            "Cheetah",
            "Chesapeake Bay Retriever",
            "Chickadee",
            "Chicken Snake",
            "Chihuahua",
            "Chimaera",
            "Chimpanzee",
            "Chinchilla",
            "Chinese Alligator",
            "Chinese Paddlefish",
            "Chinese Shar-Pei",
            "Chinook Salmon",
            "Chinstrap Penguin",
            "Chipping Sparrow",
            "Christmas Island Red Crab",
            "Cicada",
            "Cinnamon Ferret",
            "Clouded Leopard",
            "Clumber Spaniel",
            "Coachwhip Snake",
            "Coati",
            "Cobia Fish",
            "Cockalier",
            "Cockapoo",
            "Cockatiel",
            "Cockatoo",
            "Cocker Spaniel",
            "Cockroach",
            "Coelacanth",
            "Collared Peccary",
            "Collett’s Snake",
            "Colossal Squid",
            "Common Buzzard",
            "Common European Adder",
            "Common Raven",
            "Common Toad",
            "Congo Snake",
            "Cookiecutter Shark",
            "Cooper’s Hawk",
            "Copperhead",
            "Coral",
            "Coral Snake",
            "Corman Shepherd",
            "Corn Rex Cat (Cornish Rex)",
            "Corn Snake",
            "Coton de Tulear",
            "Cotton-top Tamarin",
            "Cougar",
            "Crab",
            "Crab Spider",
            "Crab-Eating Macaque",
            "Crabeater Seal",
            "Crane",
            "Crappie Fish",
            "Cross River Gorilla",
            "Crucian Carp",
            "Cuban Cockroach",
            "Curly Coated Retriever",
            "Czechoslovakian Wolfdog",
            "Dachsador",
            "Dachshund",
            "Dalmadoodle",
            "Dalmador",
            "Dalmatian",
            "Danios",
            "Dapple Dachshund",
            "Darwin’s fox",
            "Darwin’s Frog",
            "Death Adder",
            "Death’s Head Cockroach",
            "Deathwatch Beetle",
            "Deer Head Chihuahua",
            "Desert Rain Frog",
            "Deutsche Bracke",
            "Devils Coach Horse Beetle",
            "Doberman Pinscher",
            "Dogo Argentino",
            "Dogue De Bordeaux",
            "Draco Volans Lizard",
            "Dragonfish",
            "Dragonfly",
            "Dubia Cockroach",
            "Dwarf Crocodile",
            "Dwarf Hamster",
            "Eagle",
            "Earthworm",
            "Earwig",
            "Eastern Barred Bandicoot",
            "Eastern Bluebird",
            "Eastern Brown Snake",
            "Eastern Chipmunk",
            "Eastern Diamondback Rattlesnake",
            "Eastern Fence Lizard",
            "Eastern Glass Lizard",
            "Eastern Gorilla",
            "Eastern Gray Squirrel",
            "Eastern Indigo Snake",
            "Eastern Lowland Gorilla",
            "Eastern Phoebe",
            "Eastern Rat snake",
            "Eastern Woodrat",
            "Echidna",
            "Eclectus Parrot",
            "Egyptian Cobra",
            "Egyptian Goose",
            "Egyptian Mau",
            "Eland",
            "Electric Catfish",
            "Elegant Tern",
            "Elephant",
            "Elephant Seal",
            "Elephant Shrew",
            "Emerald Tree Monitor",
            "Emperor Tamarin",
            "English Cocker Spaniel",
            "English Cream Golden Retriever",
            "English Springer Spaniel",
            "Entlebucher Mountain Dog",
            "Epagneul Pont Audemer",
            "Escolar",
            "Estrela Mountain Dog",
            "Eurasian Beaver",
            "Eurasian Jay",
            "Eurasian Lynx",
            "Eurasian Nuthatch",
            "Eurasian Wolf",
            "European Bee-Eater",
            "European Polecat",
            "European Robin",
            "European Wildcat",
            "Evening Bat",
            "Eyelash Viper",
            "Falcon",
            "Fallow deer",
            "False Killer Whale",
            "False Widow Spider",
            "Fangtooth",
            "Fer-de-lance Snake",
            "Ferruginous Hawk",
            "Fiddler Crab",
            "Field Spaniel",
            "Fierce Snake",
            "Fila Brasileiro",
            "Fin Whale",
            "Fire salamander",
            "Fire-Bellied Toad",
            "Fisher Cat",
            "Fishing Cat",
            "Flamingo",
            "Flat-Coated Retriever",
            "Flea",
            "Florida Gar",
            "Florida Panther",
            "Florida Woods Cockroach",
            "Flying Snake",
            "Football Fish",
            "Formosan Mountain Dog",
            "Fossa",
            "Fox Snakes",
            "Freshwater Crocodile",
            "Freshwater Eel",
            "Freshwater Jellyfish",
            "Frigatebird",
            "Frilled Lizard",
            "Frilled Shark",
            "Fruit Bat",
            "Fur Seal",
            "Gaboon Viper",
            "Galapagos Penguin",
            "Galapagos Tortoise",
            "Gar",
            "Garden Eel",
            "Garter Snake",
            "Gazelle",
            "Geoffroys Tamarin",
            "Gerberian Shepsky",
            "German Cockroach",
            "German Pinscher",
            "German Shepherd Guide",
            "German Sheppit",
            "German Sheprador",
            "German Shorthaired Pointer",
            "German Spitz",
            "Gharial",
            "Ghost Catfish",
            "Ghost Crab",
            "Giant African Land Snail",
            "Giant Armadillo",
            "Giant Clam",
            "Giant Panda Bear",
            "Giant Salamander",
            "Giant Schnauzer",
            "Giant Schnoodle",
            "Gila Monster",
            "Giraffe",
            "Glass Frog",
            "Glass Lizard",
            "Glen Of Imaal Terrier",
            "Gnat",
            "Goat",
            "Goberian",
            "Goblin Shark",
            "Goldador",
            "Golden Lancehead",
            "Golden Lion Tamarin",
            "Golden Masked Owl",
            "Golden Saint",
            "Goliath Frog",
            "Gopher Snake",
            "Gorilla",
            "Goshawk",
            "Gouldian Finch",
            "Grass Carp",
            "Grass Snake",
            "Grasshopper",
            "Grasshopper Mouse",
            "Gray Fox",
            "Gray Tree Frog",
            "Great Blue Heron",
            "Great Crested Flycatcher",
            "Great Dane",
            "Great Danoodle",
            "Great Egret",
            "Great Pyrenees",
            "Great White Shark",
            "Greater Swiss Mountain Dog",
            "Green Anole",
            "Green Bee-Eater",
            "Green Mamba",
            "Greenland Dog",
            "Greenland Shark",
            "Grey Reef Shark",
            "Grey Seal",
            "Grizzly Bear",
            "Groenendael",
            "Ground Snake",
            "Guinea Fowl",
            "Guinea Pig",
            "Habu Snake",
            "Haddock",
            "Hagfish",
            "Halibut",
            "Hammerhead Shark",
            "Hamster",
            "Harbor Seal",
            "Hardhead Catfish",
            "Hare",
            "Harlequin Snake",
            "Harp Seal",
            "Harpy Eagle",
            "Harrier",
            "Harris Hawk",
            "Havanese",
            "Havapoo",
            "Havashire",
            "Hawaiian Crow",
            "Hawaiian Goose",
            "Hawaiian Monk Seal",
            "Hermit Crab",
            "Highland Cattle",
            "Himalayan",
            "Hippopotamus",
            "Hoary Bat",
            "Hokkaido",
            "Honduran White Bat",
            "Honey Badger",
            "Honey Buzzard",
            "Hooded Seal",
            "Horn Shark",
            "Horned Adder",
            "Horned Lizard",
            "Horseshoe Crab",
            "House Sparrow",
            "Human",
            "Humpback Whale",
            "Huntaway",
            "Huntsman Spider",
            "Huskador",
            "Huskita",
            "Husky Jack",
            "Hyena",
            "Ibizan Hound",
            "Icelandic Sheepdog",
            "Iguana",
            "Immortal Jellyfish",
            "Impala",
            "Imperial Moth",
            "Indian Cobra",
            "Indian Elephant",
            "Indian Giant Squirrel",
            "Indian Palm Squirrel",
            "Indian Rhinoceros",
            "Indian Star Tortoise",
            "Indigo Snake",
            "Irish Water Spaniel",
            "Italian Greyhound",
            "Jacana",
            "Jack Russell",
            "Jackabee",
            "Jackal",
            "Jackdaw",
            "Jackrabbit",
            "Jackson’s Chameleon",
            "Jaguar",
            "Jaguarundi Cat",
            "Japanese Beetle",
            "Japanese Chin",
            "Japanese Macaque",
            "Japanese Spitz",
            "Japanese Squirrel",
            "Japanese Terrier",
            "Javan Rhinoceros",
            "Javanese",
            "Jerboa",
            "Jonah Crab",
            "Kai Ken",
            "Kakapo",
            "Kangal",
            "Kangaroo",
            "Kangaroo Rat",
            "Keel-Billed Toucan",
            "Kenyan Sand Boa",
            "Keta Salmon",
            "Kiko Goat",
            "Killer Whale",
            "Kinder Goat",
            "King Cobra",
            "King Crab",
            "King Snake",
            "Kinkajou",
            "Kirtland’s snake",
            "Koala",
            "Komodo Dragon",
            "Kookaburra",
            "Kori Bustard",
            "Kuvasz",
            "Labahoula",
            "Labmaraner",
            "Labradane",
            "Labradoodle",
            "Labrador Retriever",
            "Labraheeler",
            "Ladybug",
            "Lake Sturgeon",
            "Lakeland Terrier",
            "LaMancha Goat",
            "Lamprey",
            "Lancashire Heeler",
            "Lappet-faced Vulture",
            "Lapponian Herder",
            "Lawnmower Blenny",
            "Lazarus Lizard",
            "Leaf-Tailed Gecko",
            "Leatherback Sea Turtle",
            "Leopard",
            "Leopard Cat",
            "Leopard Frog",
            "Leopard Gecko",
            "Leopard Lizard",
            "Leopard Seal",
            "Leopard Tortoise",
            "Lhasa Apso",
            "Lhasapoo",
            "Lion’s Mane Jellyfish",
            "Little Brown Bat",
            "Lizard",
            "Lizardfish",
            "Llama",
            "Loach",
            "Lone Star Tick",
            "Long-Eared Owl",
            "Long-Haired Rottweiler",
            "Long-Tailed Tit",
            "Longnose Gar",
            "Macaque",
            "Macaroni Penguin",
            "Macaw",
            "Mackenzie Wolf",
            "Madagascar Hissing Cockroach",
            "Magellanic Penguin",
            "Maggot",
            "Magpie",
            "Mahi Mahi (Dolphin Fish)",
            "Maine Coon",
            "Malayan Civet",
            "Malayan Tiger",
            "Mallard",
            "Malteagle",
            "Maltese",
            "Maltese Shih Tzu",
            "Maltipoo",
            "Mamba",
            "Mamushi Snake",
            "Man of War Jellyfish",
            "Manatee",
            "Manchester Terrier",
            "Mandrill",
            "Maned Wolf",
            "Mangrove Snake",
            "Manta Ray",
            "Mantella Frog",
            "Marabou Stork",
            "Marble Fox",
            "Marine Iguana",
            "Marine Toad",
            "Markhor",
            "Marmoset",
            "Marmot",
            "Marsh Frog",
            "Masked Palm Civet",
            "Massasauga",
            "Mastador",
            "Mastiff",
            "Mayfly",
            "Meagle",
            "Mealybug",
            "Meerkat",
            "Megalodon",
            "Megamouth Shark",
            "Mekong Giant Catfish",
            "Mexican Alligator Lizard",
            "Mexican Black Kingsnake",
            "Mexican Eagle (Northern crested caracara)",
            "Mexican Free-Tailed Bat",
            "Mexican Mole Lizard",
            "Midget Faded Rattlesnake",
            "Milk Snake",
            "Mini Labradoodle",
            "Miniature Bull Terrier",
            "Miniature Husky",
            "Miniature Pinscher",
            "Minke Whale",
            "Moccasin Snake",
            "Mojarra",
            "Mojave Rattlesnake",
            "Mola mola (Ocean Sunfish)",
            "Mole Snake",
            "Monarch Butterfly",
            "Monitor Lizard",
            "Monte Iberia Eleuth",
            "Moray Eel",
            "Moscow Watchdog",
            "Mountain Bluebird",
            "Mountain Cur",
            "Mountain Feist",
            "Mountain Gorilla",
            "Mountain Lion",
            "Mud Snake",
            "Mulga Snake",
            "Muntjac",
            "Muskrat",
            "Mussurana Snake",
            "Myna Bird",
            "Naked Mole Rat",
            "Narwhal",
            "Natterjack",
            "Neanderthal",
            "Neapolitan Mastiff",
            "Newfoundland",
            "Nicobar pigeon",
            "Nigerian Goat",
            "Night Adder",
            "Nightingale",
            "Nilgai",
            "North American Black Bear",
            "Northern Alligator Lizard",
            "Northern Cardinal",
            "Northern Fur Seal",
            "Northern Water Snake",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwegian Forest",
            "Norwegian Lundehund",
            "Nova Scotia Duck Tolling Retriever",
            "Nubian Goat",
            "Nudibranch",
            "Numbat",
            "Nurse Shark",
            "Nyala",
            "Oak Toad",
            "Okapi",
            "Olive Baboon",
            "Orang-utan",
            "Orange-Crowned Warbler",
            "Orb Weaver",
            "Ortolan Bunting",
            "Oscar Fish",
            "Oyster Toadfish",
            "Paddlefish",
            "Pademelon",
            "Painted Turtle",
            "Pangolin",
            "Panther",
            "Papillon",
            "Parakeet",
            "Parrot",
            "Parrot Snake",
            "Parrotfish",
            "Parrotlet",
            "Parson Russell Terrier",
            "Patas Monkey",
            "Patterdale Terrier",
            "Peacock",
            "Peacock Butterfly",
            "Peacock Spider",
            "Peagle",
            "Peekapoo",
            "Pelican",
            "Pennsylvania Wood Cockroach",
            "Pere Davids Deer",
            "Peregrine Falcon",
            "Peringuey’s Adder",
            "Perro De Presa Canario",
            "Persian",
            "Peruvian Inca Orchid",
            "Pesquet’s Parrot (Dracula Parrot)",
            "Petit Basset Griffon Vendéen",
            "Pheasant",
            "Pied Ball Python",
            "Pied Tamarin",
            "Pika",
            "Pileated Woodpecker",
            "Pine Marten",
            "Pine Snake",
            "Pine Snake",
            "Pink Fairy Armadillo",
            "Piranha",
            "Pitador",
            "Platypus",
            "Pocket Beagle",
            "Poison Dart Frog",
            "Polar Bear",
            "Polecat",
            "Polish Lowland Sheepdog",
            "Pomapoo",
            "Pomeagle",
            "Pomeranian",
            "Pond Skater",
            "Porbeagle Shark",
            "Prairie Dog",
            "Prairie Rattlesnake",
            "Prawn",
            "Praying Mantis",
            "Puff Adder",
            "Pugapoo",
            "Puma",
            "Pygmy Hippopotamus",
            "Pygmy Marmoset (Finger Monkey)",
            "Pygora Goat",
            "Pyrador",
            "Quagga",
            "Quail",
            "Queen snake",
            "Quetzal",
            "Quokka",
            "Rabbit",
            "Raccoon",
            "Raccoon Dog",
            "Radiated Tortoise",
            "Ragamuffin",
            "Ragdoll",
            "Raggle",
            "Rainbow Boa",
            "Rat",
            "Rat Snakes",
            "Rat Terrier",
            "Rattlesnake",
            "Red Diamondback Rattlesnake",
            "Red Knee Tarantula",
            "Red Panda",
            "Red Tail Boa (common boa)",
            "Red-Bellied Black Snake",
            "Red-Billed Quelea Bird",
            "Red-Eared Slider",
            "Red-handed Tamarin",
            "Red-Headed Vulture",
            "Red-Lipped Batfish",
            "Red-winged blackbird",
            "Redback Spider",
            "Redtail Catfish",
            "Reef Shark",
            "Rhombic Egg-Eater Snake",
            "Ribbon Snake",
            "Rinkhals Snake",
            "River Jack Snake",
            "Rock Crab",
            "Rock Hyrax",
            "Rose-breasted Grosbeak",
            "Roseate Spoonbill",
            "Rough Green Snake",
            "Royal Penguin",
            "Rubber Boa",
            "Ruby-Throated Hummingbird",
            "Russian Bear Dog",
            "Russian Blue",
            "Russian Tortoise",
            "Saanen Goat",
            "Saarloos Wolfdog",
            "Saber-Toothed Tiger",
            "Sable",
            "Sable Black German Shepherd",
            "Sable Ferret",
            "Saiga",
            "Saint Berdoodle",
            "Saint Bernard",
            "Saint Shepherd",
            "Salamander",
            "Salmon",
            "Salmon Shark",
            "Saluki",
            "Sambar",
            "Samoyed",
            "Sand Crab",
            "Sand Lizard",
            "Sand Tiger Shark",
            "Sand Viper",
            "Saola",
            "Sardines",
            "Satanic leaf-tailed gecko",
            "Savanna Goat",
            "Savannah Sparrow",
            "Sawfish",
            "Scarlet Kingsnake",
            "Scarlet Macaw",
            "Schneagle",
            "Scimitar-horned Oryx",
            "Sea Anemone",
            "Sea Dragon",
            "Sea Eagle",
            "Sea Lion",
            "Sea Otter",
            "Sea Roach",
            "Sea Slug",
            "Sea Squirt",
            "Sea Turtle",
            "Sea Urchin",
            "Seagull",
            "Seahorse",
            "Seal",
            "Sealyham Terrier",
            "Sei Whale",
            "Senegal Parrot",
            "Serval",
            "Shark",
            "Sharp-Tailed Snake",
            "Sheepadoodle",
            "Shepadoodle",
            "Shepkita",
            "Shiba Inu",
            "Siamese",
            "Siberian",
            "Siberian Husky",
            "Siberian Ibex",
            "Siberian Retriever",
            "Siberian Tiger",
            "Silver Dollar",
            "Silver Labrador",
            "Sixgill shark",
            "Skate Fish",
            "Skink Lizard",
            "Skipjack Tuna",
            "Sleeper Shark",
            "Smokybrown Cockroach",
            "Snail",
            "Snake",
            "Snapping Turtle",
            "Snouted Cobra",
            "Snow Crab",
            "Snow Leopard",
            "Snowshoe Hare",
            "Sockeye Salmon",
            "Somali",
            "Song Sparrow",
            "South China Tiger",
            "Southern Black Racer",
            "Southern Pacific Rattlesnake",
            "Spadefoot Toad",
            "Spanador",
            "Spanish Goat",
            "Spanish Mastiff",
            "Sparrow",
            "Sparrowhawk",
            "Spectacled Bear",
            "Sperm Whale",
            "Spider Ball Python",
            "Spider Wasp",
            "Spider-Tailed Horned Viper",
            "Spinner Shark",
            "Spinone Italiano",
            "Spitting Cobra",
            "Spixs Macaw",
            "Spotted Gar",
            "Spotted Lanternfly",
            "Springador",
            "Squash Beetle",
            "Sri Lankan Elephant",
            "Stabyhoun",
            "Staffordshire Bull Terrier",
            "Stag Beetle",
            "Standard Schnauzer",
            "Star-nosed mole",
            "Starfish",
            "Stargazer Fish",
            "Steelhead Salmon",
            "Steller’s Sea Cow",
            "Stiletto Snake",
            "Stingray",
            "Stoat",
            "Stone Crab",
            "Striped Hyena",
            "Sugar Glider",
            "Sulcata Tortoise",
            "Sumatran Elephant",
            "Sumatran Orang-utan",
            "Sumatran Rhinoceros",
            "Sumatran Tiger",
            "Sun Bear",
            "Swai Fish",
            "Swan",
            "Swedish Vallhund",
            "Syrian Hamster",
            "Taco Terrier",
            "Takin",
            "Tamaskan",
            "Tang",
            "Tapanuli Orang-utan",
            "Tapir",
            "Tarantula Hawk",
            "Tarpon",
            "Tarsier",
            "Tasmanian Devil",
            "Tasmanian Tiger",
            "Tawny Owl",
            "Teddy Bear Hamster",
            "Tennessee Walker Horse",
            "Tetra",
            "Texas Heeler",
            "Texas Indigo Snake",
            "Texas Rat Snake",
            "Texas Spiny Lizard",
            "Thai Ridgeback",
            "Tibetan Fox",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Tiffany",
            "Tiger Rattlesnake",
            "Tiger Salamander",
            "Tiger Shark",
            "Timber Rattlesnake (Canebrake Rattlesnake)",
            "Tire Track Eel",
            "Toadfish",
            "Toucan",
            "Transylvanian Hound",
            "Tree Kangaroo",
            "Tree Snake",
            "Tree swallow",
            "Treeing Walker Coonhound",
            "Tuatara",
            "Tuna",
            "Turkish Angora",
            "Twig Snake",
            "Uakari",
            "Uinta Ground Squirrel",
            "Umbrellabird",
            "Unau (Linnaeus’s Two-Toed Sloth)",
            "Ural owl",
            "Urutu Snake",
            "Utonagan",
            "Vampire Bat",
            "Vampire Squid",
            "Vaquita",
            "Venus Flytrap",
            "Vicuña",
            "Vinegaroon",
            "Viper shark (dogfish)",
            "Virgin Islands Dwarf Gecko",
            "Vizsla",
            "Volpino Italiano",
            "Wahoo Fish",
            "Walking Catfish",
            "Wallaby",
            "Walleye Fish",
            "Walrus",
            "Wandering Albatross",
            "Warthog",
            "Wasp",
            "Water Buffalo",
            "Water Dragon",
            "Water Vole",
            "Weasel",
            "Weaver Bird",
            "Weimaraner",
            "Weimardoodle",
            "Wels Catfish",
            "West Highland Terrier",
            "Western Diamondback Rattlesnake",
            "Western Gorilla",
            "Western Hognose Snake",
            "Western Lowland Gorilla",
            "Western Rat Snake",
            "Whale Shark",
            "Wheaten Terrier",
            "Whinchat",
            "Whiptail Lizard",
            "White Ferret / Albino Ferrets",
            "White-Faced Capuchin",
            "White-tail deer",
            "White-Tailed Eagle",
            "Whooping Crane",
            "Wild Boar",
            "Willow Warbler",
            "Wirehaired Pointing Griffon",
            "Wolf Snake",
            "Wombat",
            "Woodrat",
            "Woolly Mammoth",
            "Worm Snake",
            "Wrasse",
            "Wyoming Toad",
            "X-Ray Tetra",
            "Yak",
            "Yakutian Laika",
            "Yarara",
            "Yellow Anaconda",
            "Yellow Sac Spider",
            "Yellow Spotted Lizard",
            "Yellowfin Tuna",
            "Yeti Crab",
            "Yoranian",
            "Zebra",
            "Zebra Finch",
            "Zebra Mussels",
            "Zebra Pleco",
            "Zebra Shark",
            "Zebra Snake",
            "Aardwolf",
            "Adelie Penguin",
            "Aesculapian snake",
            "African Bullfrog",
            "African Bush Elephant",
            "African Clawed Frog",
            "African Forest Elephant",
            "African Palm Civet",
            "African Wild Dog",
            "Agama Lizard",
            "Airedale Terrier",
            "Airedoodle",
            "Alabai",
            "Alaskan Husky",
            "Alaskan Klee Kai",
            "Alaskan Malamute",
            "Alaskan Shepherd",
            "Albacore Tuna",
            "Albatross",
            "Aldabra Giant Tortoise",
            "Alligator",
            "Alligator Gar",
            "Alpaca",
            "Alpine Dachsbracke",
            "Alpine Goat",
            "Alusky",
            "Amazon River Dolphin (Pink Dolphin)",
            "Ambrosia Beetle",
            "American Alsatian",
            "American Bulldog",
            "American Cocker Spaniel",
            "American Hairless Terrier",
            "American Leopard Hound",
            "American Pit Bull Terrier",
            "American Water Spaniel",
            "Amur Leopard",
            "Anatolian Shepherd Dog",
            "Angelfish",
            "Anglerfish",
            "Anole Lizard",
            "Antarctic scale worm",
            "Antelope",
            "Appenzeller Dog",
            "Apple Head Chihuahua",
            "Arafura File Snake",
            "Arctic Wolf",
            "Arizona Black Rattlesnake",
            "Armadillo",
            "Armadillo Lizard",
            "Aruba Rattlesnake",
            "Asian Elephant",
            "Asian Palm Civet",
            "Asiatic Black Bear",
            "Aussiedoodle",
            "Australian Bulldog",
            "Australian Cattle Dog",
            "Australian Cockroach",
            "Australian Gecko",
            "Australian Kelpie Dog",
            "Australian Labradoodle",
            "Australian Mist",
            "Australian Retriever",
            "Australian Shepherd",
            "Australian Terrier",
            "Axolotl",
            "Bactrian Camel",
            "Bald Eagle",
            "Baleen Whale",
            "Balinese",
            "Balkan Lynx",
            "Ball Python",
            "Banana Ball Python",
            "Banana Eel",
            "Banded Palm Civet",
            "Barn Owl",
            "Barn Swallow",
            "Barnacle",
            "Barred Owl",
            "Basilisk Lizard",
            "Bassetoodle",
            "Beabull",
            "Beagle",
            "Beagle Shepherd",
            "Beaglier",
            "Bearded Collie",
            "Bearded Vulture",
            "Bedlington Terrier",
            "Beefalo",
            "Beetle",
            "Belgian Shepherd",
            "Belgian Tervuren",
            "Beluga Sturgeon",
            "Bengal Tiger",
            "Bernedoodle",
            "Bilby",
            "Biscuit Beetle",
            "Black And Tan Coonhound",
            "Black Mamba",
            "Black Marlin",
            "Black Rat Snake",
            "Black Rhinoceros",
            "Black Russian Terrier",
            "Black Wasp",
            "Black Widow Spider",
            "Black-Capped Chickadee",
            "Black-Footed Ferret",
            "Blackpoll Warbler",
            "Blanket Octopus",
            "Blister Beetle",
            "Blobfish",
            "Blood Python",
            "Bloodhound",
            "Blue Belly Lizard",
            "Blue Catfish",
            "Blue grosbeak",
            "Blue Iguana",
            "Blue Jay",
            "Blue Lacy Dog",
            "Blue Picardy Spaniel",
            "Blue Shark",
            "Blue Tit",
            "Blue Whale",
            "Blue-Ringed Octopus",
            "Bluefin Tuna",
            "Bluegill",
            "Bluetick Coonhound",
            "Bobolink",
            "Boggle",
            "Boglen Terrier",
            "Bolognese Dog",
            "Boomslang",
            "Border Collie",
            "Bordoodle",
            "Borneo Elephant",
            "Bottlenose Dolphin",
            "Bouvier Des Flandres",
            "Bowhead Whale",
            "Box Turtle",
            "Boxerdoodle",
            "Boxweiler",
            "Boykin Spaniel",
            "Brazilian Terrier",
            "Brussels Griffon",
            "Buffalo",
            "Bull Shark",
            "Bull Terrier",
            "Bull Trout",
            "Bulldog",
            "Bullfrog",
            "Bullmastiff",
            "Bullsnake",
            "Bumblebee",
            "Burrowing Owl",
            "Butterfly",
            "Butterfly Fish",
            "Caecilian",
            "Caiman Lizard",
            "Camel",
            "Camel Cricket",
            "Camel Spider",
            "Canada Lynx",
            "Cantil",
            "Cape Lion",
            "Caracal",
            "Carolina Dog",
            "Carolina Parakeet",
            "Cascabel",
            "Catahoula Leopard",
            "Catalan Sheepdog",
            "Caterpillar",
            "Cavalier King Charles Spaniel",
            "Chameleon",
            "Cheagle",
            "Chinchilla",
            "Chinese Alligator",
            "Chinese Paddlefish",
            "Chinook Salmon",
            "Christmas Island Red Crab",
            "Cichlid",
            "Cinereous Vulture",
            "Clouded Leopard",
            "Clownfish",
            "Clumber Spaniel",
            "Cockalier",
            "Cockatiel",
            "Cocker Spaniel",
            "Coelacanth",
            "Collared Peccary",
            "Collett’s Snake",
            "Collie",
            "Colossal Squid",
            "Common Furniture Beetle",
            "Common Loon",
            "Conger Eel",
            "Coral",
            "Coral Snake",
            "Coton de Tulear",
            "Crabeater Seal",
            "Crocodile",
            "Cross River Gorilla",
            "Curly Coated Retriever",
            "Cuttlefish",
            "Czechoslovakian Wolfdog",
            "Dalmadoodle",
            "Dalmador",
            "Dalmatian",
            "Dapple Dachshund",
            "Deathwatch Beetle",
            "Desert Locust",
            "Devils Coach Horse Beetle",
            "Dhole",
            "Dolphin",
            "Double Doodle",
            "Doxle",
            "Draco Volans Lizard",
            "Dragonfly",
            "Dung Beetle",
            "Dusky Dolphin",
            "Dwarf Crocodile",
            "Eagle",
            "Eastern Bluebird",
            "Eastern Diamondback Rattlesnake",
            "Eastern Fence Lizard",
            "Eastern Glass Lizard",
            "Eastern Gorilla",
            "Eastern Gray Squirrel",
            "Eastern Lowland Gorilla",
            "Eclectus Parrot",
            "Edible Frog",
            "Eel",
            "Eland",
            "Electric Catfish",
            "Electric Eel",
            "Elegant Tern",
            "Elephant",
            "Elephant Seal",
            "Elephant Shrew",
            "Elk",
            "Emerald Tree Monitor",
            "English Bulldog",
            "English Cocker Spaniel",
            "English Cream Golden Retriever",
            "English Foxhound",
            "English Pointer",
            "English Setter",
            "English Shepherd",
            "English Springer Spaniel",
            "Entlebucher Mountain Dog",
            "Epagneul Pont Audemer",
            "Escolar",
            "Estrela Mountain Dog",
            "Eurasian Lynx",
            "Eurasian Wolf",
            "European Polecat",
            "European Wildcat",
            "Eyelash Viper",
            "Falcon",
            "Fallow deer",
            "False Killer Whale",
            "False Widow Spider",
            "Fer-de-lance Snake",
            "Fiddler Crab",
            "Field Spaniel",
            "Fila Brasileiro",
            "Fin Whale",
            "Fire Eel",
            "Fire salamander",
            "Fire-Bellied Toad",
            "Firefly",
            "Flamingo",
            "Flat-Coated Retriever",
            "Flea",
            "Florida Gar",
            "Florida Panther",
            "Florida Woods Cockroach",
            "Flounder",
            "Flowerhorn Fish",
            "Fluke Fish (summer flounder)",
            "Fly",
            "Flying Fish",
            "Flying Lemur",
            "Flying Snake",
            "Flying Squirrel",
            "Football Fish",
            "Fox Squirrel",
            "French Bulldog",
            "Frengle",
            "Freshwater Crocodile",
            "Freshwater Eel",
            "Freshwater Jellyfish",
            "Frilled Lizard",
            "Frilled Shark",
            "Fruit Fly",
            "Fur Seal",
            "Galapagos Penguin",
            "Galapagos Tortoise",
            "Garden Eel",
            "Gazelle",
            "Gerbil",
            "Gharial",
            "Giant African Land Snail",
            "Giant Armadillo",
            "Giant Clam",
            "Giant Salamander",
            "Giant Schnoodle",
            "Gila Monster",
            "Glass Frog",
            "Glass Lizard",
            "Glechon",
            "Glen Of Imaal Terrier",
            "Glow Worm",
            "Goblin Shark",
            "Goldador",
            "Golden Dox",
            "Golden Lancehead",
            "Golden Lion Tamarin",
            "Golden Masked Owl",
            "Golden Newfie",
            "Golden Oriole",
            "Golden Pyrenees",
            "Golden Retriever",
            "Golden Saint",
            "Golden Shepherd",
            "Golden-Crowned Flying Fox",
            "Goldendoodle",
            "Goldfish",
            "Goliath Frog",
            "Gorilla",
            "Gouldian Finch",
            "Great Blue Heron",
            "Great Crested Flycatcher",
            "Great Danoodle",
            "Green Anole",
            "Greenland Dog",
            "Greenland Shark",
            "Grey Mouse Lemur",
            "Grey Seal",
            "Griffon Vulture",
            "Grizzly Bear",
            "Groenendael",
            "Guinea Fowl",
            "Halibut",
            "Harbor Seal",
            "Harlequin Snake",
            "Harp Seal",
            "Harpy Eagle",
            "Hawaiian Monk Seal",
            "Hellbender",
            "Hercules Beetle",
            "Highland Cattle",
            "Himalayan",
            "Hooded Seal",
            "Hornbill",
            "Horned Lizard",
            "Horsefly",
            "Housefly",
            "Howler Monkey",
            "Humboldt Penguin",
            "Humboldt Squid",
            "Humpback Whale",
            "Huskydoodle",
            "Icelandic Sheepdog",
            "Immortal Jellyfish",
            "Impala",
            "Imperial Moth",
            "Indian Elephant",
            "Indian Giant Squirrel",
            "Indian Palm Squirrel",
            "Irish Doodle",
            "Irish Water Spaniel",
            "Irish WolfHound",
            "Italian Greyhound",
            "Ivory-billed woodpecker",
            "Jack Russell",
            "Jackal",
            "Jackson’s Chameleon",
            "Japanese Beetle",
            "Japanese Squirrel",
            "Jellyfish",
            "Junglefowl",
            "Kangal",
            "Keel-Billed Toucan",
            "Kerry Blue Terrier",
            "Kestrel",
            "Keta Salmon",
            "Killer Whale",
            "King Vulture",
            "Kirtland’s snake",
            "Koala",
            "Koolie",
            "Krill",
            "Labahoula",
            "Labmaraner",
            "Labradane",
            "Labradoodle",
            "Labrador Retriever",
            "Labraheeler",
            "Ladybug",
            "Lake Sturgeon",
            "Lakeland Terrier",
            "LaMancha Goat",
            "Lamprey",
            "Lancashire Heeler",
            "Lappet-faced Vulture",
            "Lapponian Herder",
            "Lawnmower Blenny",
            "Lazarus Lizard",
            "Leaf-Tailed Gecko",
            "Leatherback Sea Turtle",
            "Leech",
            "Lemming",
            "Lemur",
            "Leonberger",
            "Leopard",
            "Leopard Cat",
            "Leopard Frog",
            "Leopard Gecko",
            "Leopard Lizard",
            "Leopard Seal",
            "Leopard Tortoise",
            "Lhasa Apso",
            "Lhasapoo",
            "Liger",
            "Lion",
            "Lion’s Mane Jellyfish",
            "Lionfish",
            "Little Brown Bat",
            "Little Penguin",
            "Lizard",
            "Lizardfish",
            "Llama",
            "Loach",
            "Lobster",
            "Locust",
            "Lone Star Tick",
            "Long-Eared Owl",
            "Long-Haired Rottweiler",
            "Long-Tailed Tit",
            "Longnose Gar",
            "Lorikeet",
            "Lowchen",
            "Lumpfish",
            "Lungfish",
            "Lynx",
            "Lyrebird",
            "Mackenzie Wolf",
            "Magellanic Penguin",
            "Mahi Mahi (Dolphin Fish)",
            "Malayan Civet",
            "Malayan Tiger",
            "Mallard",
            "Malteagle",
            "Maltese",
            "Maltese Shih Tzu",
            "Maltipoo",
            "Man of War Jellyfish",
            "Mandrill",
            "Maned Wolf",
            "Mantella Frog",
            "Marble Fox",
            "Masked Palm Civet",
            "Mayfly",
            "Meagle",
            "Mealybug",
            "Megalodon",
            "Mexican Alligator Lizard",
            "Mexican Black Kingsnake",
            "Mexican Eagle (Northern crested caracara)",
            "Mexican Free-Tailed Bat",
            "Mexican Mole Lizard",
            "Midget Faded Rattlesnake",
            "Milk Snake",
            "Milkfish",
            "Millipede",
            "Mini Labradoodle",
            "Miniature Bull Terrier",
            "Minke Whale",
            "Mojave Rattlesnake",
            "Mola mola (Ocean Sunfish)",
            "Mole",
            "Mole Cricket",
            "Mole Snake",
            "Molly",
            "Monarch Butterfly",
            "Mongrel",
            "Monitor Lizard",
            "Monte Iberia Eleuth",
            "Moon Jellyfish",
            "Moray Eel",
            "Mountain Bluebird",
            "Mountain Gorilla",
            "Mountain Lion",
            "Mule",
            "Mulga Snake",
            "Naked Mole Rat",
            "Narwhal",
            "Neanderthal",
            "Neapolitan Mastiff",
            "Nebelung",
            "Needlefish",
            "Newfoundland",
            "Nightingale",
            "Nile Crocodile",
            "Nilgai",
            "Norfolk Terrier",
            "North American Black Bear",
            "Northern Alligator Lizard",
            "Northern Cardinal",
            "Northern Fur Seal",
            "Norwegian Elkhound",
            "Norwegian Lundehund",
            "Nova Scotia Duck Tolling Retriever",
            "Nyala",
            "Ocelot",
            "Old English Sheepdog",
            "Olive Baboon",
            "Olm",
            "Orange-Crowned Warbler",
            "Ortolan Bunting",
            "Owl",
            "Paddlefish",
            "Pademelon",
            "Painted Turtle",
            "Pangolin",
            "Papillon",
            "Parrotlet",
            "Parson Russell Terrier",
            "Patterdale Terrier",
            "Peacock Butterfly",
            "Peagle",
            "Pelican",
            "Pembroke Welsh Corgi",
            "Pennsylvania Wood Cockroach",
            "Peregrine Falcon",
            "Pesquet’s Parrot (Dracula Parrot)",
            "Petite Goldendoodle",
            "Pied Ball Python",
            "Pileated Woodpecker",
            "Pink Fairy Armadillo",
            "Pit Bull",
            "Platypus",
            "Pocket Beagle",
            "Pocket Pitbull",
            "Polar Bear",
            "Polecat",
            "Polish Lowland Sheepdog",
            "Polyphemus moth",
            "Pomeagle",
            "Poodle",
            "Poogle",
            "Pool Frog",
            "Porbeagle Shark",
            "Prairie Rattlesnake",
            "Pudelpointer",
            "Puggle",
            "Purple Emperor Butterfly",
            "Purple Finch",
            "Pyredoodle",
            "Quail",
            "Quetzal",
            "Quoll",
            "Ragdoll",
            "Raggle",
            "Rattlesnake",
            "Red Diamondback Rattlesnake",
            "Red Knee Tarantula",
            "Red Squirrel",
            "Red Tail Boa (common boa)",
            "Red Wolf",
            "Red-Bellied Black Snake",
            "Red-Billed Quelea Bird",
            "Red-Eared Slider",
            "Red-Headed Vulture",
            "Red-Lipped Batfish",
            "Red-winged blackbird",
            "Redtail Catfish",
            "Ribbon Eel",
            "Rinkhals Snake",
            "River Turtle",
            "Roseate Spoonbill",
            "Rottweiler",
            "Royal Penguin",
            "Russell Terrier",
            "Russian Blue",
            "Saarloos Wolfdog",
            "Sable",
            "Sable Black German Shepherd",
            "Sable Ferret",
            "Saint Berdoodle",
            "Salamander",
            "Salmon",
            "Salmon Shark",
            "Saluki",
            "Sand Lizard",
            "Saola",
            "Satanic leaf-tailed gecko",
            "Scarlet Kingsnake",
            "Scarlet Macaw",
            "Schneagle",
            "Schnoodle",
            "Sea Eagle",
            "Sea Lion",
            "Sea Slug",
            "Sea Turtle",
            "Seagull",
            "Seal",
            "Sealyham Terrier",
            "Sei Whale",
            "Senegal Parrot",
            "Serval",
            "Sharp-Tailed Snake",
            "Sheepadoodle",
            "Shepadoodle",
            "Shepweiler",
            "Shoebill Stork",
            "Shollie",
            "Silkie Chicken",
            "Silky Terrier",
            "Silver Dollar",
            "Silver Labrador",
            "Sixgill shark",
            "Skink Lizard",
            "Sleeper Shark",
            "Sloth",
            "Slow Worm",
            "Slug",
            "Snail",
            "Snapping Turtle",
            "Snow Leopard",
            "Snowy Owl",
            "Sockeye Salmon",
            "Somali",
            "Southern Black Racer",
            "Southern Pacific Rattlesnake",
            "Spectacled Bear",
            "Sperm Whale",
            "Spider Ball Python",
            "Spider-Tailed Horned Viper",
            "Spinone Italiano",
            "Spiny Hill Turtle",
            "Spotted Lanternfly",
            "Springerdoodle",
            "Squash Beetle",
            "Squirrel",
            "Squirrel Monkey",
            "Squirrelfish",
            "Sri Lankan Elephant",
            "Staffordshire Bull Terrier",
            "Stag Beetle",
            "Star-nosed mole",
            "Steelhead Salmon",
            "Steller’s Sea Cow",
            "Stiletto Snake",
            "Sugar Glider",
            "Sulcata Tortoise",
            "Sumatran Elephant",
            "Swedish Vallhund",
            "Tapanuli Orang-utan",
            "Tarantula Hawk",
            "Tasmanian Devil",
            "Tawny Owl",
            "Teddy Roosevelt Terrier",
            "Telescope Fish",
            "Tennessee Walker Horse",
            "Tenterfield Terrier",
            "Texas Heeler",
            "Texas Spiny Lizard",
            "Thorny Devil",
            "Tibetan Spaniel",
            "Tiger Beetle",
            "Tiger Rattlesnake",
            "Tiger Salamander",
            "Timber Rattlesnake (Canebrake Rattlesnake)",
            "Tire Track Eel",
            "Toy Poodle",
            "Transylvanian Hound",
            "Tree swallow",
            "Treeing Tennessee Brindle",
            "Treeing Walker Coonhound",
            "Tsetse Fly",
            "Turtles",
            "Uinta Ground Squirrel",
            "Umbrellabird",
            "Unau (Linnaeus’s Two-Toed Sloth)",
            "Ural owl",
            "Venus Flytrap",
            "Virgin Islands Dwarf Gecko",
            "Vizsla",
            "Volpino Italiano",
            "Vulture",
            "Walking Catfish",
            "Wallaby",
            "Walleye Fish",
            "Walrus",
            "Wandering Albatross",
            "Water Buffalo",
            "Water Vole",
            "Weasel",
            "Weimardoodle",
            "Wels Catfish",
            "Welsh Corgi",
            "Welsh Terrier",
            "West Highland Terrier",
            "Western Diamondback Rattlesnake",
            "Western Gorilla",
            "Western Lowland Gorilla",
            "Whale Shark",
            "Whiptail Lizard",
            "White Butterfly",
            "White Ferret / Albino Ferrets",
            "White-tail deer",
            "White-Tailed Eagle",
            "Whoodle",
            "Wild Boar",
            "Wildebeest",
            "Willow Warbler",
            "Wolf",
            "Wolf Eel",
            "Wolf Snake",
            "Wolf Spider",
            "Wolffish",
            "Wolverine",
            "Wood Turtle",
            "Woodlouse",
            "Woodlouse Spider",
            "Woolly Mammoth",
            "Woolly Monkey",
            "Xoloitzcuintli",
            "Yakutian Laika",
            "Yellow Anaconda",
            "Yellow Sac Spider",
            "Yellow Spotted Lizard",
            "Yellow-Eyed Penguin",
            "Yellowfin Tuna",
            "Zebra Mussels",
            "Zebra Pleco");
}
