---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.1
    app.quarkus.io/commit-id: d214f47ac6596595761cd79cb20095cdeed347b0
    app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/spiritanimals-bff.git
    app.quarkus.io/build-timestamp: 2024-06-13 - 14:30:13 +0000
  labels:
    app.kubernetes.io/name: spiritanimals-bff
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: spiritanimals-bff
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8090
  selector:
    app.kubernetes.io/name: spiritanimals-bff
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.1
    app.quarkus.io/commit-id: d214f47ac6596595761cd79cb20095cdeed347b0
    app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/spiritanimals-bff.git
    app.quarkus.io/build-timestamp: 2024-06-13 - 14:30:13 +0000
  labels:
    app.kubernetes.io/name: spiritanimals-bff
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: spiritanimals-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spiritanimals-bff
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.11.1
        app.quarkus.io/commit-id: d214f47ac6596595761cd79cb20095cdeed347b0
        app.quarkus.io/vcs-uri: https://github.com/jeremyrdavis/spiritanimals-bff.git
        app.quarkus.io/build-timestamp: 2024-06-13 - 14:30:13 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: spiritanimals-bff
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/jeremyrdavis/spiritanimals-bff:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: spiritanimals-bff
          ports:
            - containerPort: 8090
              name: http
              protocol: TCP
