name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -DOPENAI_API_KEY=foobarbazkey clean package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build --file src/main/docker/Dockerfile.jvm -t spiritanimals-monolith .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag spiritanimals-monolith ${{ secrets.DOCKERHUB_USERNAME }}/spiritanimals-monolith:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spiritanimals-monolith:latest